# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Person.create(name: 'Barack Obama', twitter_handle: 'BarackObama', instagram_name: 'barackobama')
Person.create(name: 'Kevin Hart', twitter_handle: 'kevinhart4real', instagram_name: 'kevinhart4real')
Person.create(name: 'Lebron James', twitter_handle: 'kingjames', instagram_name: 'kingjames')
Person.create(name: 'Drake', twitter_handle: 'drake', instagram_name: 'champagnepapi')
Person.create(name: 'J.R. Smith', twitter_handle: 'therealjrsmith', instagram_name: 'therealjrsmith')
Person.create(name: 'Floyd Mayweather', twitter_handle: 'floydmayweather', instagram_name: 'floydmayweather')
Person.create(name: 'Tony Hawk', twitter_handle: 'tonyhawk', instagram_name: 'tonyhawk')
Person.create(name: 'Chad Ochocinco', twitter_handle: 'ochocinco', instagram_name: 'ochocinco')
Person.create(name: 'Michael Phelps', twitter_handle: 'MichaelPhelps', instagram_name: 'm_phelps00')
Person.create(name: 'Carmelo Anthony', twitter_handle: 'carmeloanthony', instagram_name: 'carmeloanthony')
Person.create(name: 'Russell Westbrook', twitter_handle: 'russwest44', instagram_name: 'russwest44')
Person.create(name: 'Neymar Júnior', twitter_handle: 'neymarjr', instagram_name: 'neymarjr')
Person.create(name: 'Justin Timberlake', twitter_handle: 'justintimberlake', instagram_name: 'justintimberlake')
Person.create(name: 'Katy Perry', twitter_handle: 'katyperry', instagram_name: 'katyperry')
Person.create(name: 'Cristiano Ronaldo', twitter_handle: 'cristiano', instagram_name: 'cristiano')
Person.create(name: 'Sean Diddy Combs', twitter_handle: 'iamdiddy', instagram_name: 'iamdiddy')
Person.create(name: 'Miranda Kerr', twitter_handle: 'mirandakerr', instagram_name: 'mirandakerr')
Person.create(name: 'Channing Tatum', twitter_handle: 'channingtatum', instagram_name: 'channingtatum')
Person.create(name: 'Lady Gaga', twitter_handle: 'ladygaga', instagram_name: 'ladygaga')
Person.create(name: 'Jessica Alba', twitter_handle: 'jessicaalba', instagram_name: 'jessicaalba')
Person.create(name: 'Wiz Khalifa', twitter_handle: 'wizkhalifa', instagram_name: 'mistercap')
Person.create(name: 'Snoop Dogg', twitter_handle: 'snoopdogg', instagram_name: 'snoopdogg')
Person.create(name: 'The Rock', twitter_handle: 'therock', instagram_name: 'therock')
Person.create(name: 'Dwyane Wade', twitter_handle: 'dwyanewade', instagram_name: 'dwyanewade')
Person.create(name: 'Macklemore', twitter_handle: 'macklemore', instagram_name: 'macklemore')
Person.create(name: 'Zooey Deschanel', twitter_handle: 'zooeydeschanel', instagram_name: 'zooeydeschanel')
Person.create(name: 'Bruno Mars', twitter_handle: 'brunomars', instagram_name: 'brunomars')
Person.create(name: 'Kevin Durant', twitter_handle: 'kdtrey5', instagram_name: 'easymoneysniper')
Person.create(name: 'Serena Williams', twitter_handle: 'serenawilliams', instagram_name: 'serenawilliams')
Person.create(name: 'DeSean Jackson', twitter_handle: 'DeSeanJackson10', instagram_name: '0ne0fone')
Person.create(name: 'Mike Tyson', twitter_handle: 'miketyson', instagram_name: 'miketyson')
Person.create(name: 'Usain Bolt', twitter_handle: 'usainbolt', instagram_name: 'usainbolt')
Person.create(name: 'Michelle Wie', twitter_handle: 'themichellewie', instagram_name: 'themichellewie')
Person.create(name: 'Kelly Slater', twitter_handle: 'kellyslater', instagram_name: 'kellyslater')
Person.create(name: 'Brad Richards', twitter_handle: 'BRichards_1991', instagram_name: 'brichards_1991')
Person.create(name: 'Tyreke Evans', twitter_handle: 'tyrekeevans', instagram_name: 'tyrekeevans')
Person.create(name: 'Kevin Love', twitter_handle: 'kevinlove', instagram_name: 'kevinlove')
Person.create(name: 'Kaka', twitter_handle: 'kaka', instagram_name: 'kaka')
Person.create(name: 'Chris Paul', twitter_handle: 'CP3', instagram_name: 'cp3')
Person.create(name: 'James Harden', twitter_handle: 'jharden13', instagram_name: 'jharden13')
Person.create(name: 'Sean Penn', twitter_handle: 'SeanPenn', instagram_name: 'SeanPenn')
Person.create(name: 'Jimmy Fallon', twitter_handle: 'jimmyfallon', instagram_name: 'jimmyfallon')
Person.create(name: 'Tiger Woods', twitter_handle: 'tigerwoods', instagram_name: 'tigerwoods')
Person.create(name: 'Jeremy Piven', twitter_handle: 'jeremypiven', instagram_name: 'howulivinjpiven')
Person.create(name: 'Oprah Winfrey', twitter_handle: 'oprah', instagram_name: 'oprah')
Person.create(name: 'Ashton Kutcher', twitter_handle: 'aplusk', instagram_name: 'mrkatalyst')
Person.create(name: 'Aaron Paul', twitter_handle: 'aaronpaul_8', instagram_name: 'glassofwhiskey')
Person.create(name: 'Justin Bieber', twitter_handle: 'justinbieber', instagram_name: 'justinbieber')
Person.create(name: 'Kim Kardashian', twitter_handle: 'kimkardashian', instagram_name: 'kimkardashian')
Person.create(name: 'Rihanna', twitter_handle: 'rihanna', instagram_name: 'badgalriri')
Person.create(name: 'Beyonce', twitter_handle: 'beyonce', instagram_name: 'beyonce')
Person.create(name: 'Ariana Grande', twitter_handle: 'arianagrande', instagram_name: 'arianagrande')
Person.create(name: 'Miley Cyrus', twitter_handle: 'mileycyrus', instagram_name: 'mileycyrus')
Person.create(name: 'Kendall Jenner', twitter_handle: 'kendalljenner', instagram_name: 'kendalljenner')
Person.create(name: 'Taylor Swift', twitter_handle: 'taylorswift', instagram_name: 'taylorswift')
Person.create(name: 'Akon', twitter_handle: 'Akon', instagram_name: 'akon')
Person.create(name: 'Tyga', twitter_handle: 'tyga', instagram_name: 'kinggoldchains')
Person.create(name: 'Nicki Minaj', twitter_handle: 'nickiminaj', instagram_name: 'nickiminaj')
